logger:
  file:
    path: /tmp/model5g-runs/b0-order123-v2/smf1.log
  level: info
global:
  max:
    ue: 1024
    peer: 128
smf:
  sbi:
    server:
    - address: 127.0.0.4
      port: 7777
    client:
      scp:
      - uri: http://127.0.0.200:7777
      nrf:
      - uri: http://127.0.0.10:7777
      delegated:
        nrf:
          nfm: 'no'
          disc: 'no'
  pfcp:
    server:
    - address: 127.0.0.4
    client:
      upf:
      - address: 127.0.0.7
  gtpc:
    server:
    - address: 127.0.0.4
  gtpu:
    server:
    - address: 127.0.0.4
  metrics:
    server:
    - address: 127.0.0.4
      port: 9090
  session:
  - subnet: 10.45.1.0/24
    gateway: 10.45.1.1
  dns:
  - 8.8.8.8
  - 8.8.4.4
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  mtu: 1400
  info:
  - s_nssai:
    - sst: 1
      dnn:
      - internet
    tai:
    - plmn_id:
        mcc: '999'
        mnc: '70'
      tac: 1
