logger:
  file:
    path: /work/runs/patched-preflight/upf.log
  level: info
global:
  max:
    ue: 1024
    peer: 128
upf:
  pfcp:
    server:
    - address: 127.0.0.7
    client: null
  gtpu:
    server:
    - address: 127.0.0.7
  session:
  - subnet: 10.45.0.0/16
    gateway: 10.45.0.1
  metrics:
    server:
    - address: 127.0.0.7
      port: 9090
